services:
  analyzer:
    build: ./analyzer
    container_name: birdnet-analyzer
    restart: unless-stopped
    env_file: .env
    ports:
      - "5001:5001"
    volumes:
      - ./audio:/audio
      - ./results:/results
      - ./rclone-config:/config/rclone
      - ./analyzer-cache:/usr/local/lib/python3.11/site-packages/birdnet_analyzer/checkpoints
      - ./custom_scripts:/custom_scripts
      - ./logs:/logs

  receiver:
    build: ./receiver
    container_name: birdnet-receiver
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/logs
    depends_on:
      - analyzer